import { PlatformProductItem } from "./platformProducts";

export const PLATFORM_PRODUCTS: PlatformProductItem[] = [
  {
    name: "Buy Crypto",
    description: "Fiat gateway",
    iconUrl: "buyCrypto.svg",
    comingSoon: false,
    new: true,
    inProgress: false,
    link: "/fiat-gateway",
  },
  {
    name: "Staking",
    description: "Stake & Earn",
    iconUrl: "stake.svg",
    comingSoon: false,
    inProgress: false,
    new: false,
    link: "/staking",
  },
  {
    name: "Bridge",
    description: "Token migration",
    iconUrl: "swap.svg",
    comingSoon: false,
    inProgress: false,
    new: false,
    link: "/bridge",
  },
  {
    name: "Wallet",
    description: "Manage Assets",
    iconUrl: "wallet.svg",
    comingSoon: false,
    inProgress: false,
    new: false,
    link: "/wallet",
  },
  {
    name: "Web3 Chat",
    description: "Launch Chat",
    iconUrl: "chat.svg",
    comingSoon: false,
    new: false,
    inProgress: true,
    link: "/chat",
  },
  {
    name: "Explorer",
    description: "Block Explorer",
    iconUrl: "explorer.svg",
    comingSoon: false,
    inProgress: true,
    new: false,
    link: "/explorer/casper",
  },
  {
    name: "Marketplace",
    description: "Trade NFTs",
    iconUrl: "marketplace.svg",
    comingSoon: false,
    new: false,
    inProgress: true,
    link: "",
  },

  {
    name: "Guilds",
    description: "Join team",
    iconUrl: "guilds.svg",
    comingSoon: true,
    new: false,
    inProgress: false,
    link: "",
  },
  {
    name: "DEX",
    description: "Swap / LP",
    iconUrl: "bridge.svg",
    comingSoon: true,
    inProgress: false,
    new: false,
    link: "",
  },
];
